-- ==============================================================================
-- TrackStudy Database Schema (Corrected, Connected & Automated)
-- Generated by: Senior Database Architect
-- Date: 2026-01-04
-- Version: 2.3 (Added Phone Support to User Creation Trigger)
-- ==============================================================================

-- 0. CLEANUP
drop table if exists public.offline_sync_queue cascade;
drop table if exists public.enrollments cascade;
drop table if exists public.lessons cascade;
drop table if exists public.courses cascade;
drop table if exists public.profiles cascade;

drop table if exists public.tick_logs cascade;
drop table if exists public.onboarding_progress cascade;
drop table if exists public.resource_defaults cascade;
drop table if exists public.users cascade;

-- Drops functions
drop function if exists public.handle_updated_at() cascade;
drop function if exists public.handle_new_user() cascade;

-- 1. UTILITY FUNCTIONS
-- ==============================================================================
create or replace function public.handle_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 2. TABLES STRUCTURE
-- ==============================================================================

-- Table: users
create table public.users (
  id text primary key, -- The Username/Custom ID (e.g., "adnan" OR Phone Number)
  auth_id uuid references auth.users(id) on delete cascade not null,
  settings jsonb default '{}'::jsonb,
  data jsonb default '{}'::jsonb,
  password text, -- Legacy support
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  
  constraint users_auth_id_key unique (auth_id)
);

-- Table: resource_defaults
create table public.resource_defaults (
  id integer primary key,
  "order" integer not null,
  key text not null unique,
  label text not null,
  color text not null,
  created_at timestamp with time zone default now()
);

-- Table: tick_logs
create table public.tick_logs (
  id uuid default gen_random_uuid() primary key,
  user_id text references public.users(id) on delete cascade not null,
  box_id text not null,
  subject_id text not null,
  chapter_id text not null,
  field_key text not null references public.resource_defaults(key) on update cascade,
  percent_before numeric,
  percent_after numeric,
  source text default 'manual',
  comment text,
  timestamp timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

-- Table: onboarding_progress
create table public.onboarding_progress (
  user_id text references public.users(id) on delete cascade not null,
  tour_id text not null,
  completed boolean default false,
  skipped boolean default false,
  completed_at timestamp with time zone default now(),
  primary key (user_id, tour_id)
);

-- 3. ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================

alter table public.users enable row level security;
alter table public.tick_logs enable row level security;
alter table public.resource_defaults enable row level security;
alter table public.onboarding_progress enable row level security;

-- Policies for USERS
create policy "Users can view own profile"
  on public.users for select
  using (auth_id = auth.uid());

create policy "Users can update own profile"
  on public.users for update
  using (auth_id = auth.uid());

create policy "Users can insert own profile"
  on public.users for insert
  with check (auth_id = auth.uid());

-- Policies for TICK_LOGS
create policy "Users can view own logs"
  on public.tick_logs for select
  using (
    user_id in (
      select id from public.users where auth_id = auth.uid()
    )
  );

create policy "Users can insert own logs"
  on public.tick_logs for insert
  with check (
    user_id in (
      select id from public.users where auth_id = auth.uid()
    )
  );

-- Policies for RESOURCE_DEFAULTS
create policy "Authenticated users can read defaults"
  on public.resource_defaults for select
  using (auth.role() = 'authenticated');

-- Policies for ONBOARDING_PROGRESS
create policy "Users can manage own onboarding"
  on public.onboarding_progress for all
  using (
    user_id in (
      select id from public.users where auth_id = auth.uid()
    )
  );


-- 4. AUTOMATION & DEFAULTS
-- ==============================================================================

create trigger on_update_users
  before update on public.users
  for each row execute procedure public.handle_updated_at();

-- Trigger: Create user on Signup (Bypasses RLS)
-- Updated to handle Phone Numbers as Usernames
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  username text;
begin
  -- Priority 1: Custom Disply Name (Metadata)
  username := new.raw_user_meta_data->>'displayName';
  
  -- Priority 2: Phone Number
  if username is null then
      username := new.phone;
  end if;

  -- Priority 3: Email Prefix
  if username is null then
      username := split_part(new.email, '@', 1);
  end if;
  
  -- Fallback: Auth ID
  if username is null then
      username := new.id;
  end if;

  insert into public.users (id, auth_id, settings, data)
  values (
    username,
    new.id,
    '{}'::jsonb, 
    jsonb_build_object('username', username)
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- Seed Default Resources
insert into public.resource_defaults (id, "order", key, label, color)
values 
  (1, 1, 'mainbook', 'Lecture', 'bg-sky-500'),
  (2, 2, 'class', 'Book', 'bg-blue-500'),
  (3, 3, 'revclass', 'Resource 1', 'bg-indigo-500'),
  (4, 4, 'meditrics', 'Resource 2', 'bg-teal-500'),
  (5, 5, 'mqb', 'Resource 3', 'bg-amber-500'),
  (6, 6, 'sfexam', 'Resource 4', 'bg-rose-500'),
  (7, 7, 'rev1', 'Resource 5', 'bg-violet-500'),
  (8, 8, 'rev2', 'Resource 6', 'bg-purple-500')
on conflict (id) do nothing;

-- End of Schema Script
